version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: medicadebolso-postgres
    environment:
      POSTGRES_DB: medicadebolso
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - medicadebolso-network

  mongodb:
    image: mongo:6
    container_name: medicadebolso-mongodb
    environment:
      MONGO_INITDB_DATABASE: medicadebolso
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - medicadebolso-network

  redis:
    image: redis:7
    container_name: medicadebolso-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - medicadebolso-network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    container_name: medicadebolso-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - medicadebolso-network

  kafka:
    image: confluentinc/cp-kafka:7.3.0
    container_name: medicadebolso-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - medicadebolso-network

volumes:
  postgres_data:
  mongodb_data:
  redis_data:

networks:
  medicadebolso-network:
    driver: bridge 